import { setRequestLocale } from 'next-intl/server';

export default async function EditorialPolicyPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <article className="max-w-3xl mx-auto px-4 py-12 article-content">
      <h1 className="font-display text-4xl font-bold mb-4">Editorial Policy</h1>
      <p className="text-xl text-ink-600 mb-8">
        Our standards for sourcing, accuracy, transparency, and corrections.
      </p>

      <h2>Source Whitelist</h2>
      <p>
        We only cover information that originates from one of the following categories:
      </p>
      <ul>
        <li>Indian government press releases (PIB, ministry websites, ISRO, etc.)</li>
        <li>Official corporate communications and product blogs (e.g. Google, Microsoft, OpenAI, Amazon, Cloudflare)</li>
        <li>Press release distribution networks (PR Newswire, GlobeNewswire)</li>
        <li>Public news APIs used only for trend detection — never for republishing</li>
      </ul>
      <p>
        We do not scrape commercial newspapers, premium news services, or paywalled content. We do not
        republish article text or headlines from such sources.
      </p>

      <h2>Writing Process</h2>
      <p>
        Each article on Dinand News is generated by extracting verifiable facts from a primary source and
        rewriting them into a fresh, structured explainer. Every article includes:
      </p>
      <ul>
        <li>A two-line summary</li>
        <li>Key highlights as bullet points</li>
        <li>"What happened" — fact-based reconstruction in our own words</li>
        <li>"Why it matters" — context and significance</li>
        <li>"What comes next" — implications and likely follow-ups</li>
        <li>A clearly attributed link to the primary source</li>
      </ul>

      <h2>Use of AI</h2>
      <p>
        We use AI tools — including large language models — to help draft summaries and translate articles
        into India's major languages. AI is a drafting and translation aid, not a source of facts. Articles
        are reviewed against this editorial policy before publication. We disclose AI assistance on every
        article.
      </p>

      <h2>Accuracy Standards</h2>
      <p>
        Facts must be verifiable in the cited source. We do not extrapolate beyond what the source states.
        When information is uncertain or not yet confirmed, we say so explicitly.
      </p>

      <h2>Corrections</h2>
      <p>
        If we discover or are notified of an error, we will:
      </p>
      <ul>
        <li>Correct the article promptly</li>
        <li>Add a "Correction" note explaining what changed and when</li>
        <li>Reply to the person who flagged the error</li>
      </ul>
      <p>
        See our <a href={`/${locale}/fact-check-policy`}>Fact Check Policy</a> for the full process.
      </p>

      <h2>Independence</h2>
      <p>
        Editorial decisions are made independently of advertisers. We do not accept payment to cover, omit,
        or favorably frame any story. Sponsored content, when present, is clearly labeled.
      </p>

      <h2>Diversity of Coverage</h2>
      <p>
        We aim to cover government, technology, business, startups, sports, entertainment, and other topics
        of interest to Indian readers. Coverage choices are guided by reader interest and source
        availability, not by political affiliation.
      </p>

      <h2>Contact the Editor</h2>
      <p>
        Questions, story tips, or feedback: <a href="mailto:editorial@autoflowa.in">editorial@autoflowa.in</a>
      </p>
    </article>
  );
}
